apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 82225592-ingress
spec:
  ingressClassName: ingress-internal
  rules:
  - host: 82225592-82225592.cepg-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: my-82225592
            port:
              number: 8080
        pathType: Prefix